[theme]
base = "light"
primaryColor = "#FB7185"
backgroundColor = "#FFF0F5"
secondaryBackgroundColor = "#FFE4E6"
textColor = "#18181B"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
runOnSave = true
headless = true

